#!/bin/bash

alias kin.event='tmux-cssh -ns lion0{33,49,70,71,72,73}'
alias kin.queue='tmux-cssh -ns tiger55{0,1}'
alias kin.analyzer='tmux-cssh -ns fox57{3,4}'
alias kin.query='tmux-cssh -ns fox57{1,2}'
alias kin.api='tmux-cssh -ns fox20{7,8}'
alias kin.openapi='tmux-cssh -ns ptom26{4,5}'
alias kin.batch='tmux-cssh -ns fox576'

alias kp.alpha='tmux-cssh -ns kpusher-{alpha,sandbox}-vm{1,2}'
alias kp.gcm='tmux-cssh -ns {pg,gs}-kpusher-gcm{001..005}'
alias kp.apns='tmux-cssh -ns {kpp,gs-kpusher}-apns{001..008}'
alias kp.aom='tmux-cssh -ns {pg,gs}-kpusher-aom001'
alias kp.capri='tmux-cssh -ns kpusher-capri-{gcm,apns}{001..002}'

alias ki.event='tmux-cssh -ns kinsight-event-{pg,gs}{01..03}'
alias ki.mq='tmux-cssh -ns kinsight-rmq-{pg,gs}01'
alias ki.analyzer='tmux-cssh -ns kinsight-analyzer-{pg,gs}01'
alias ki.api='tmux-cssh -ns kinsight-api-{pg,gs}01'
alias ki.openapi='tmux-cssh -ns kinsight-release{01..02}'
alias ki.batch='tmux-cssh -ns kinsight-batch-gs01'
