#!/bin/bash

alias ki.event='tmux-cssh -ns kinsight-event-{gs,pg}{01..03}'
alias ki.analyzer='tmux-cssh -ns kinsight-analyzer-{gs,pg}01'
alias ki.api='tmux-cssh -ns kinsight-api-gs{01,02}'
alias ki.openapi='tmux-cssh -ns kinsight-release{01..02}'
alias ki.batch='tmux-cssh -ns kinsight-batch-gs01'

alias kp.alpha='tmux-cssh -ns kpusher-{alpha,sandbox}-vm{1,2}'
alias kp.gcm='tmux-cssh -ns {gs,pg}-kpusher-gcm{001..005}'
alias kp.apns='tmux-cssh -ns {gs-kpusher,kpp}-apns{001..008}'
alias kp.aom='tmux-cssh -ns {gs,pg}-kpusher-aom001'
alias kp.capri='tmux-cssh -ns kpusher-capri-{apns,gcm}{001,002}'
alias kp.mq='tmux-cssh -ns {gs,pg}-kpusher-mq{001..020}'
alias kp.feedback='tmux-cssh -ns kpusher-feedback{001,002}'
alias kp.ci='tmux-cssh -ns pg-kpusher-ci001'
alias kp.papi='tmux-cssh -ns ghost{620,623} kpusher-papi{001..004}'
