#!/bin/bash -eux
test -n "${1:-}"
exec openssl req -x509 -out "$1".crt -keyout "$1".key \
	-newkey rsa:2048 -nodes -sha256 -days 36500 \
	-subj "/CN=$1" -extensions EXT -config <( \
		printf "[dn]\nCN=$1\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:$1\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
