#!/bin/bash -eu

test $# = 0 && {
	echo "usage: $0 [user@]host ..."
	exit 2
} >&2

test $# = 1 && exec ssh "$1"

set -x

commands=()
for host in "${@:2}"; do
	commands+=(\; splitw "ssh $host" \; selectl tiled)
done

exec tmux new -n "$1..${@: -1}{$#}" "ssh $1" "${commands[@]}" \; setw synchronize-panes on
