#!/bin/bash -eu

test $# = 0 && {
	echo "usage: $0 [user@]host ..."
	exit 2
} >&2

test $# = 1 && exec ssh "$1"

set -x

commands=(new -n "$1..${@: -1}{$#}" "ssh $1")
for host in "${@:2}"; do
	commands+=(\; splitw "ssh $host" \; selectl tiled)
done

exec tmux "${commands[@]}" \; setw synchronize-panes on
